/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Retrieve all dependents for a user
 */
export const getAllDependentsQueryParams = zod.object({
  "id": zod.string().optional().describe('Filter dependents by ID'),
  "name": zod.string().optional().describe('Filter dependents by name')
})

export const getAllDependentsResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "result": zod.array(zod.string())
})

/**
 * @summary Create a new dependent
 */
export const createDependentBody = zod.object({
  "name": zod.string()
})

/**
 * @summary Retrieve a specific dependent by ID or name
 */
export const findDependentQueryParams = zod.object({
  "id": zod.string().optional().describe('Dependent ID'),
  "name": zod.string().optional().describe('Dependent name')
})

export const findDependentResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "result": zod.object({

})
})

/**
 * @summary Update a dependent
 */
export const updateDependentParams = zod.object({
  "id": zod.string().describe('Dependent ID')
})

export const updateDependentBody = zod.object({
  "name": zod.string()
})

export const updateDependentResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "data": zod.object({

})
})

/**
 * @summary Delete a dependent
 */
export const deleteDependentParams = zod.object({
  "id": zod.string().describe('Dependent ID')
})

export const deleteDependentResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "data": zod.object({

})
})

