/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateDependentDto,
  FindDependentParams,
  GetAllDependentsParams,
  ResponseBadRequestDto,
  ResponseForbiddenDto,
  ResponseInternalServerErrorDto,
  ResponseNotFoundDto,
  ResponseUnauthorizedDto,
  ResultCreateDependentDto,
  ResultDeleteCardDto,
  ResultFindAllDependentDto,
  ResultFindOneDependentDto,
  ResultUpdateDependentDto,
  UpdateDependentDto,
} from "../../model";

import { customInstance } from "../../../lib/axios";
import type { ErrorType, BodyType } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Retrieve all dependents for a user
 */
export const getAllDependents = (
  params?: GetAllDependentsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResultFindAllDependentDto>(
    { url: `/dependents`, method: "GET", params, signal },
    options,
  );
};

export const getGetAllDependentsQueryKey = (
  params?: GetAllDependentsParams,
) => {
  return [`/dependents`, ...(params ? [params] : [])] as const;
};

export const getGetAllDependentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllDependents>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: GetAllDependentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllDependents>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAllDependentsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllDependents>>
  > = ({ signal }) => getAllDependents(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllDependents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllDependentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllDependents>>
>;
export type GetAllDependentsQueryError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseNotFoundDto
  | ResponseInternalServerErrorDto
>;

export function useGetAllDependents<
  TData = Awaited<ReturnType<typeof getAllDependents>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params: undefined | GetAllDependentsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllDependents>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllDependents>>,
          TError,
          Awaited<ReturnType<typeof getAllDependents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllDependents<
  TData = Awaited<ReturnType<typeof getAllDependents>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: GetAllDependentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllDependents>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllDependents>>,
          TError,
          Awaited<ReturnType<typeof getAllDependents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllDependents<
  TData = Awaited<ReturnType<typeof getAllDependents>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: GetAllDependentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllDependents>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Retrieve all dependents for a user
 */

export function useGetAllDependents<
  TData = Awaited<ReturnType<typeof getAllDependents>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: GetAllDependentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllDependents>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllDependentsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new dependent
 */
export const createDependent = (
  createDependentDto: BodyType<CreateDependentDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResultCreateDependentDto>(
    {
      url: `/dependents`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createDependentDto,
      signal,
    },
    options,
  );
};

export const getCreateDependentMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDependent>>,
    TError,
    { data: BodyType<CreateDependentDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createDependent>>,
  TError,
  { data: BodyType<CreateDependentDto> },
  TContext
> => {
  const mutationKey = ["createDependent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createDependent>>,
    { data: BodyType<CreateDependentDto> }
  > = (props) => {
    const { data } = props ?? {};

    return createDependent(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateDependentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createDependent>>
>;
export type CreateDependentMutationBody = BodyType<CreateDependentDto>;
export type CreateDependentMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Create a new dependent
 */
export const useCreateDependent = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createDependent>>,
      TError,
      { data: BodyType<CreateDependentDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createDependent>>,
  TError,
  { data: BodyType<CreateDependentDto> },
  TContext
> => {
  const mutationOptions = getCreateDependentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Retrieve a specific dependent by ID or name
 */
export const findDependent = (
  params?: FindDependentParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResultFindOneDependentDto>(
    { url: `/dependents/search`, method: "GET", params, signal },
    options,
  );
};

export const getFindDependentQueryKey = (params?: FindDependentParams) => {
  return [`/dependents/search`, ...(params ? [params] : [])] as const;
};

export const getFindDependentQueryOptions = <
  TData = Awaited<ReturnType<typeof findDependent>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindDependentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findDependent>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindDependentQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findDependent>>> = ({
    signal,
  }) => findDependent(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof findDependent>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindDependentQueryResult = NonNullable<
  Awaited<ReturnType<typeof findDependent>>
>;
export type FindDependentQueryError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseNotFoundDto
  | ResponseInternalServerErrorDto
>;

export function useFindDependent<
  TData = Awaited<ReturnType<typeof findDependent>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params: undefined | FindDependentParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findDependent>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findDependent>>,
          TError,
          Awaited<ReturnType<typeof findDependent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindDependent<
  TData = Awaited<ReturnType<typeof findDependent>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindDependentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findDependent>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findDependent>>,
          TError,
          Awaited<ReturnType<typeof findDependent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindDependent<
  TData = Awaited<ReturnType<typeof findDependent>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindDependentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findDependent>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Retrieve a specific dependent by ID or name
 */

export function useFindDependent<
  TData = Awaited<ReturnType<typeof findDependent>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindDependentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findDependent>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindDependentQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update a dependent
 */
export const updateDependent = (
  id: string,
  updateDependentDto: BodyType<UpdateDependentDto>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ResultUpdateDependentDto>(
    {
      url: `/dependents/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateDependentDto,
    },
    options,
  );
};

export const getUpdateDependentMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateDependent>>,
    TError,
    { id: string; data: BodyType<UpdateDependentDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateDependent>>,
  TError,
  { id: string; data: BodyType<UpdateDependentDto> },
  TContext
> => {
  const mutationKey = ["updateDependent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateDependent>>,
    { id: string; data: BodyType<UpdateDependentDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateDependent(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateDependentMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateDependent>>
>;
export type UpdateDependentMutationBody = BodyType<UpdateDependentDto>;
export type UpdateDependentMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Update a dependent
 */
export const useUpdateDependent = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateDependent>>,
      TError,
      { id: string; data: BodyType<UpdateDependentDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateDependent>>,
  TError,
  { id: string; data: BodyType<UpdateDependentDto> },
  TContext
> => {
  const mutationOptions = getUpdateDependentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a dependent
 */
export const deleteDependent = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ResultDeleteCardDto>(
    { url: `/dependents/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteDependentMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDependent>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteDependent>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteDependent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteDependent>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteDependent(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteDependentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteDependent>>
>;

export type DeleteDependentMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Delete a dependent
 */
export const useDeleteDependent = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteDependent>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteDependent>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteDependentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
