/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateCardDto,
  FindAllCardsParams,
  FindOneCardParams,
  ResponseBadRequestDto,
  ResponseForbiddenDto,
  ResponseInternalServerErrorDto,
  ResponseNotFoundDto,
  ResponseUnauthorizedDto,
  ResultCreateCardDto,
  ResultDeleteCardDto,
  ResultFindAllCardDto,
  ResultFindOneCardDto,
  ResultUpdateCardDto,
  UpdateCardDto,
} from "../../model";

import { customInstance } from "../../../lib/axios";
import type { ErrorType, BodyType } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Retrieve all cards for the authenticated user
 */
export const findAllCards = (
  params?: FindAllCardsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResultFindAllCardDto>(
    { url: `/cards`, method: "GET", params, signal },
    options,
  );
};

export const getFindAllCardsQueryKey = (params?: FindAllCardsParams) => {
  return [`/cards`, ...(params ? [params] : [])] as const;
};

export const getFindAllCardsQueryOptions = <
  TData = Awaited<ReturnType<typeof findAllCards>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindAllCardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findAllCards>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindAllCardsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findAllCards>>> = ({
    signal,
  }) => findAllCards(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof findAllCards>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindAllCardsQueryResult = NonNullable<
  Awaited<ReturnType<typeof findAllCards>>
>;
export type FindAllCardsQueryError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseNotFoundDto
  | ResponseInternalServerErrorDto
>;

export function useFindAllCards<
  TData = Awaited<ReturnType<typeof findAllCards>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params: undefined | FindAllCardsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findAllCards>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllCards>>,
          TError,
          Awaited<ReturnType<typeof findAllCards>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindAllCards<
  TData = Awaited<ReturnType<typeof findAllCards>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindAllCardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findAllCards>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllCards>>,
          TError,
          Awaited<ReturnType<typeof findAllCards>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindAllCards<
  TData = Awaited<ReturnType<typeof findAllCards>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindAllCardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findAllCards>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Retrieve all cards for the authenticated user
 */

export function useFindAllCards<
  TData = Awaited<ReturnType<typeof findAllCards>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindAllCardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findAllCards>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindAllCardsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new card for the authenticated user
 */
export const createCard = (
  createCardDto: BodyType<CreateCardDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResultCreateCardDto>(
    {
      url: `/cards`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCardDto,
      signal,
    },
    options,
  );
};

export const getCreateCardMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCard>>,
    TError,
    { data: BodyType<CreateCardDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCard>>,
  TError,
  { data: BodyType<CreateCardDto> },
  TContext
> => {
  const mutationKey = ["createCard"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCard>>,
    { data: BodyType<CreateCardDto> }
  > = (props) => {
    const { data } = props ?? {};

    return createCard(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCardMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCard>>
>;
export type CreateCardMutationBody = BodyType<CreateCardDto>;
export type CreateCardMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Create a new card for the authenticated user
 */
export const useCreateCard = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCard>>,
      TError,
      { data: BodyType<CreateCardDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCard>>,
  TError,
  { data: BodyType<CreateCardDto> },
  TContext
> => {
  const mutationOptions = getCreateCardMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Retrieve a single card based on id or name. At least one parameter is required
 */
export const findOneCard = (
  params?: FindOneCardParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResultFindOneCardDto>(
    { url: `/cards/search`, method: "GET", params, signal },
    options,
  );
};

export const getFindOneCardQueryKey = (params?: FindOneCardParams) => {
  return [`/cards/search`, ...(params ? [params] : [])] as const;
};

export const getFindOneCardQueryOptions = <
  TData = Awaited<ReturnType<typeof findOneCard>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindOneCardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findOneCard>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindOneCardQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findOneCard>>> = ({
    signal,
  }) => findOneCard(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof findOneCard>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindOneCardQueryResult = NonNullable<
  Awaited<ReturnType<typeof findOneCard>>
>;
export type FindOneCardQueryError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseNotFoundDto
  | ResponseInternalServerErrorDto
>;

export function useFindOneCard<
  TData = Awaited<ReturnType<typeof findOneCard>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params: undefined | FindOneCardParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findOneCard>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findOneCard>>,
          TError,
          Awaited<ReturnType<typeof findOneCard>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindOneCard<
  TData = Awaited<ReturnType<typeof findOneCard>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindOneCardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findOneCard>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findOneCard>>,
          TError,
          Awaited<ReturnType<typeof findOneCard>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindOneCard<
  TData = Awaited<ReturnType<typeof findOneCard>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindOneCardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findOneCard>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Retrieve a single card based on id or name. At least one parameter is required
 */

export function useFindOneCard<
  TData = Awaited<ReturnType<typeof findOneCard>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindOneCardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findOneCard>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindOneCardQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update an existing card
 */
export const updateCard = (
  id: string,
  updateCardDto: BodyType<UpdateCardDto>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ResultUpdateCardDto>(
    {
      url: `/cards/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateCardDto,
    },
    options,
  );
};

export const getUpdateCardMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCard>>,
    TError,
    { id: string; data: BodyType<UpdateCardDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCard>>,
  TError,
  { id: string; data: BodyType<UpdateCardDto> },
  TContext
> => {
  const mutationKey = ["updateCard"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCard>>,
    { id: string; data: BodyType<UpdateCardDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateCard(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCardMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCard>>
>;
export type UpdateCardMutationBody = BodyType<UpdateCardDto>;
export type UpdateCardMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Update an existing card
 */
export const useUpdateCard = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCard>>,
      TError,
      { id: string; data: BodyType<UpdateCardDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCard>>,
  TError,
  { id: string; data: BodyType<UpdateCardDto> },
  TContext
> => {
  const mutationOptions = getUpdateCardMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a card
 */
export const deleteCard = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ResultDeleteCardDto>(
    { url: `/cards/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteCardMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCard>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCard>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteCard"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCard>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteCard(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCardMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCard>>
>;

export type DeleteCardMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Delete a card
 */
export const useDeleteCard = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCard>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCard>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteCardMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
