/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Retrieve all cards for the authenticated user
 */
export const findAllCardsQueryParams = zod.object({
  "flag": zod.string().optional().describe('Card flag'),
  "bank": zod.string().optional().describe('Bank name'),
  "dueDay": zod.string().optional().describe('Due day'),
  "payDay": zod.string().optional().describe('Pay day'),
  "name": zod.string().optional().describe('Card name')
})

export const findAllCardsResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "result": zod.array(zod.string())
})

/**
 * @summary Create a new card for the authenticated user
 */
export const createCardBody = zod.object({
  "name": zod.string(),
  "bank": zod.string(),
  "flag": zod.string(),
  "limit": zod.string(),
  "dueDay": zod.number(),
  "payDay": zod.number()
})

/**
 * @summary Retrieve a single card based on id or name. At least one parameter is required
 */
export const findOneCardQueryParams = zod.object({
  "id": zod.string().optional().describe('Card ID'),
  "name": zod.string().optional().describe('Card name'),
  "bank": zod.string().optional().describe('Bank name')
})

export const findOneCardResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "result": zod.object({

})
})

/**
 * @summary Update an existing card
 */
export const updateCardParams = zod.object({
  "id": zod.string().describe('Card ID')
})

export const updateCardBody = zod.object({
  "name": zod.string(),
  "bank": zod.string(),
  "flag": zod.string(),
  "limit": zod.string(),
  "dueDay": zod.number(),
  "payDay": zod.number()
})

export const updateCardResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "data": zod.object({

})
})

/**
 * @summary Delete a card
 */
export const deleteCardParams = zod.object({
  "id": zod.string().describe('Card ID')
})

export const deleteCardResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "data": zod.object({

})
})

