/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Login a user
 */
export const authLoginBody = zod.object({
  "email": zod.string().describe('User email'),
  "password": zod.string().describe('User password')
})

export const authLoginResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "data": zod.object({
  "provider_token": zod.object({

}).nullish(),
  "provider_refresh_token": zod.object({

}).nullish(),
  "access_token": zod.string(),
  "refresh_token": zod.string(),
  "expires_in": zod.number(),
  "expires_at": zod.number().optional(),
  "token_type": zod.string(),
  "user": zod.object({
  "id": zod.string(),
  "app_metadata": zod.object({
  "provider": zod.string(),
  "providers": zod.array(zod.string())
}),
  "user_metadata": zod.object({
  "displayName": zod.string(),
  "email": zod.string(),
  "email_verified": zod.boolean(),
  "phone": zod.string(),
  "phone_verified": zod.boolean(),
  "sub": zod.string()
}),
  "aud": zod.string(),
  "confirmation_sent_at": zod.string().optional(),
  "recovery_sent_at": zod.string().optional(),
  "email_change_sent_at": zod.string().optional(),
  "new_email": zod.string().optional(),
  "new_phone": zod.string().optional(),
  "invited_at": zod.string().optional(),
  "action_link": zod.string().optional(),
  "email": zod.string().optional(),
  "phone": zod.string().optional(),
  "created_at": zod.string(),
  "confirmed_at": zod.string().optional(),
  "email_confirmed_at": zod.string().optional(),
  "phone_confirmed_at": zod.string().optional(),
  "last_sign_in_at": zod.string().optional(),
  "role": zod.string().optional(),
  "updated_at": zod.string().optional(),
  "identities": zod.array(zod.object({
  "identity_id": zod.string(),
  "id": zod.string(),
  "user_id": zod.string(),
  "identity_data": zod.object({
  "displayName": zod.string(),
  "email": zod.string(),
  "email_verified": zod.boolean(),
  "phone": zod.string(),
  "phone_verified": zod.boolean(),
  "sub": zod.string()
}),
  "provider": zod.string(),
  "last_sign_in_at": zod.string(),
  "created_at": zod.string(),
  "updated_at": zod.string(),
  "email": zod.string()
})).optional(),
  "is_anonymous": zod.boolean().optional(),
  "is_sso_user": zod.boolean().optional()
})
})
})

