/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BaseResponseDto,
  CreateCategoryDto,
  FindCategoryParams,
  GetAllCategoriesParams,
  ResponseBadRequestDto,
  ResponseForbiddenDto,
  ResponseInternalServerErrorDto,
  ResponseNotFoundDto,
  ResponseUnauthorizedDto,
  ResultCreateCategoryDto,
  ResultDeleteCategoryDto,
  ResultFindAllCategoryDto,
  ResultFindOneCategoryDto,
  ResultUpdateCategoryDto,
  UpdateCategoryDto,
} from "../../model";

import { customInstance } from "../../../lib/axios";
import type { ErrorType, BodyType } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieve all categories for the authenticated user.
 * @summary Get all categories
 */
export const getAllCategories = (
  params?: GetAllCategoriesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResultFindAllCategoryDto>(
    { url: `/categories`, method: "GET", params, signal },
    options,
  );
};

export const getGetAllCategoriesQueryKey = (
  params?: GetAllCategoriesParams,
) => {
  return [`/categories`, ...(params ? [params] : [])] as const;
};

export const getGetAllCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllCategories>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: GetAllCategoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCategories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAllCategoriesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllCategories>>
  > = ({ signal }) => getAllCategories(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllCategories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllCategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllCategories>>
>;
export type GetAllCategoriesQueryError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseNotFoundDto
  | ResponseInternalServerErrorDto
>;

export function useGetAllCategories<
  TData = Awaited<ReturnType<typeof getAllCategories>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params: undefined | GetAllCategoriesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCategories>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCategories>>,
          TError,
          Awaited<ReturnType<typeof getAllCategories>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllCategories<
  TData = Awaited<ReturnType<typeof getAllCategories>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: GetAllCategoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCategories>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCategories>>,
          TError,
          Awaited<ReturnType<typeof getAllCategories>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllCategories<
  TData = Awaited<ReturnType<typeof getAllCategories>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: GetAllCategoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCategories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all categories
 */

export function useGetAllCategories<
  TData = Awaited<ReturnType<typeof getAllCategories>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: GetAllCategoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCategories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllCategoriesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new category
 */
export const createCategory = (
  createCategoryDto: BodyType<CreateCategoryDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResultCreateCategoryDto>(
    {
      url: `/categories`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCategoryDto,
      signal,
    },
    options,
  );
};

export const getCreateCategoryMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCategory>>,
    TError,
    { data: BodyType<CreateCategoryDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCategory>>,
  TError,
  { data: BodyType<CreateCategoryDto> },
  TContext
> => {
  const mutationKey = ["createCategory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCategory>>,
    { data: BodyType<CreateCategoryDto> }
  > = (props) => {
    const { data } = props ?? {};

    return createCategory(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCategory>>
>;
export type CreateCategoryMutationBody = BodyType<CreateCategoryDto>;
export type CreateCategoryMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Create a new category
 */
export const useCreateCategory = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCategory>>,
      TError,
      { data: BodyType<CreateCategoryDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCategory>>,
  TError,
  { data: BodyType<CreateCategoryDto> },
  TContext
> => {
  const mutationOptions = getCreateCategoryMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Add default categories for the user
 */
export const addDefaultCategories = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<BaseResponseDto>(
    { url: `/categories/add-defaults`, method: "POST", signal },
    options,
  );
};

export const getAddDefaultCategoriesMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addDefaultCategories>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addDefaultCategories>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["addDefaultCategories"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addDefaultCategories>>,
    void
  > = () => {
    return addDefaultCategories(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddDefaultCategoriesMutationResult = NonNullable<
  Awaited<ReturnType<typeof addDefaultCategories>>
>;

export type AddDefaultCategoriesMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Add default categories for the user
 */
export const useAddDefaultCategories = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addDefaultCategories>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addDefaultCategories>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAddDefaultCategoriesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Find a specific category by ID or name.
 * @summary Find a category
 */
export const findCategory = (
  params?: FindCategoryParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResultFindOneCategoryDto>(
    { url: `/categories/search`, method: "GET", params, signal },
    options,
  );
};

export const getFindCategoryQueryKey = (params?: FindCategoryParams) => {
  return [`/categories/search`, ...(params ? [params] : [])] as const;
};

export const getFindCategoryQueryOptions = <
  TData = Awaited<ReturnType<typeof findCategory>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindCategoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findCategory>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindCategoryQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findCategory>>> = ({
    signal,
  }) => findCategory(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof findCategory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindCategoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof findCategory>>
>;
export type FindCategoryQueryError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseNotFoundDto
  | ResponseInternalServerErrorDto
>;

export function useFindCategory<
  TData = Awaited<ReturnType<typeof findCategory>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params: undefined | FindCategoryParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findCategory>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findCategory>>,
          TError,
          Awaited<ReturnType<typeof findCategory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindCategory<
  TData = Awaited<ReturnType<typeof findCategory>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindCategoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findCategory>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findCategory>>,
          TError,
          Awaited<ReturnType<typeof findCategory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindCategory<
  TData = Awaited<ReturnType<typeof findCategory>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindCategoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findCategory>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Find a category
 */

export function useFindCategory<
  TData = Awaited<ReturnType<typeof findCategory>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  params?: FindCategoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findCategory>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindCategoryQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update a category
 */
export const updateCategory = (
  name: string,
  updateCategoryDto: BodyType<UpdateCategoryDto>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ResultUpdateCategoryDto>(
    {
      url: `/categories/${name}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateCategoryDto,
    },
    options,
  );
};

export const getUpdateCategoryMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCategory>>,
    TError,
    { name: string; data: BodyType<UpdateCategoryDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCategory>>,
  TError,
  { name: string; data: BodyType<UpdateCategoryDto> },
  TContext
> => {
  const mutationKey = ["updateCategory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCategory>>,
    { name: string; data: BodyType<UpdateCategoryDto> }
  > = (props) => {
    const { name, data } = props ?? {};

    return updateCategory(name, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCategory>>
>;
export type UpdateCategoryMutationBody = BodyType<UpdateCategoryDto>;
export type UpdateCategoryMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Update a category
 */
export const useUpdateCategory = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCategory>>,
      TError,
      { name: string; data: BodyType<UpdateCategoryDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCategory>>,
  TError,
  { name: string; data: BodyType<UpdateCategoryDto> },
  TContext
> => {
  const mutationOptions = getUpdateCategoryMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a category
 */
export const deleteCategory = (
  name: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ResultDeleteCategoryDto>(
    { url: `/categories/${name}`, method: "DELETE" },
    options,
  );
};

export const getDeleteCategoryMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCategory>>,
    TError,
    { name: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCategory>>,
  TError,
  { name: string },
  TContext
> => {
  const mutationKey = ["deleteCategory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCategory>>,
    { name: string }
  > = (props) => {
    const { name } = props ?? {};

    return deleteCategory(name, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCategory>>
>;

export type DeleteCategoryMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Delete a category
 */
export const useDeleteCategory = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCategory>>,
      TError,
      { name: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCategory>>,
  TError,
  { name: string },
  TContext
> => {
  const mutationOptions = getDeleteCategoryMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
