/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ResponseBadRequestDto,
  ResponseForbiddenDto,
  ResponseInternalServerErrorDto,
  ResponseNotFoundDto,
  ResponseUnauthorizedDto,
  ResultFindAllInvoiceDto,
  ResultUpdateAllInvoicesDto,
} from "../../model";

import { customInstance } from "../../../lib/axios";
import type { ErrorType } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Update all invoices
 */
export const updateAllInvoices = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResultUpdateAllInvoicesDto>(
    { url: `/invoice/update`, method: "POST", signal },
    options,
  );
};

export const getUpdateAllInvoicesMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAllInvoices>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAllInvoices>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["updateAllInvoices"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAllInvoices>>,
    void
  > = () => {
    return updateAllInvoices(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAllInvoicesMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAllInvoices>>
>;

export type UpdateAllInvoicesMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Update all invoices
 */
export const useUpdateAllInvoices = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateAllInvoices>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateAllInvoices>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getUpdateAllInvoicesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get all invoices for a user
 */
export const getUserInvoices = (
  userId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResultFindAllInvoiceDto>(
    { url: `/invoice/${userId}`, method: "GET", signal },
    options,
  );
};

export const getGetUserInvoicesQueryKey = (userId: string) => {
  return [`/invoice/${userId}`] as const;
};

export const getGetUserInvoicesQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserInvoices>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserInvoices>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserInvoicesQueryKey(userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserInvoices>>> = ({
    signal,
  }) => getUserInvoices(userId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserInvoices>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserInvoicesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserInvoices>>
>;
export type GetUserInvoicesQueryError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseNotFoundDto
  | ResponseInternalServerErrorDto
>;

export function useGetUserInvoices<
  TData = Awaited<ReturnType<typeof getUserInvoices>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  userId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserInvoices>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserInvoices>>,
          TError,
          Awaited<ReturnType<typeof getUserInvoices>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserInvoices<
  TData = Awaited<ReturnType<typeof getUserInvoices>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserInvoices>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserInvoices>>,
          TError,
          Awaited<ReturnType<typeof getUserInvoices>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserInvoices<
  TData = Awaited<ReturnType<typeof getUserInvoices>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserInvoices>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all invoices for a user
 */

export function useGetUserInvoices<
  TData = Awaited<ReturnType<typeof getUserInvoices>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserInvoices>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserInvoicesQueryOptions(userId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
