/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import type { UserAppMetadataDto } from "./userAppMetadataDto";
import type { UserMetadataDto } from "./userMetadataDto";
import type { UserIdentityDto } from "./userIdentityDto";

export interface AuthUserDto {
  id: string;
  app_metadata: UserAppMetadataDto;
  user_metadata: UserMetadataDto;
  aud: string;
  confirmation_sent_at?: string;
  recovery_sent_at?: string;
  email_change_sent_at?: string;
  new_email?: string;
  new_phone?: string;
  invited_at?: string;
  action_link?: string;
  email?: string;
  phone?: string;
  created_at: string;
  confirmed_at?: string;
  email_confirmed_at?: string;
  phone_confirmed_at?: string;
  last_sign_in_at?: string;
  role?: string;
  updated_at?: string;
  identities?: UserIdentityDto[];
  is_anonymous?: boolean;
  is_sso_user?: boolean;
}
