/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */

export interface CreateTransactionDto {
  cardId: string;
  purchaseName: string;
  purchaseCategory: string;
  description: string;
  amount: number;
  installments: number;
  readonly installmentValues: readonly string[];
  purchaseDate: string;
  dependentId: string;
}
