/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */

export type FindTransactionByFiltersParams = {
  /**
   * Transaction ID
   */
  id?: string;
  /**
   * Purchase name
   */
  purchaseName?: string;
  /**
   * Dependent ID
   */
  dependentId?: string;
  /**
   * Card ID
   */
  cardId?: string;
  /**
   * Purchase category
   */
  purchaseCategory?: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Purchase date
   */
  purchaseDate?: string;
};
