/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */

export type GetAllTransactionsParams = {
  /**
   * Card ID
   */
  card?: string;
  /**
   * Dependent ID
   */
  dependent?: string;
  /**
   * Purchase name
   */
  purchaseName?: string;
  /**
   * Purchase category
   */
  purchaseCategory?: string;
  /**
   * Purchase date
   */
  purchaseDate?: string;
  /**
   * Number of installments
   */
  installments?: string;
  /**
   * Installment dates. E.g. 02/2025, 05/2025
   */
  installmentDates?: string;
};
