/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import type { ResponseNotFoundDtoData } from "./responseNotFoundDtoData";

export interface ResponseNotFoundDto {
  success: boolean;
  statusCode: number;
  count: number;
  message: string;
  data: ResponseNotFoundDtoData;
}
