/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import type { ResultCreateCategoryDtoData } from "./resultCreateCategoryDtoData";

export interface ResultCreateCategoryDto {
  success: boolean;
  message: string;
  statusCode: number;
  count: number;
  data: ResultCreateCategoryDtoData;
}
