/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import type { SessionDtoProviderToken } from "./sessionDtoProviderToken";
import type { SessionDtoProviderRefreshToken } from "./sessionDtoProviderRefreshToken";
import type { AuthUserDto } from "./authUserDto";

export interface SessionDto {
  /** @nullable */
  provider_token?: SessionDtoProviderToken;
  /** @nullable */
  provider_refresh_token?: SessionDtoProviderRefreshToken;
  access_token: string;
  refresh_token: string;
  expires_in: number;
  expires_at?: number;
  token_type: string;
  user: AuthUserDto;
}
