/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserDto {
  /** Name of the user */
  name?: string;
  /** Email of the user */
  email?: string;
  phone: string;
}
