/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */

export interface UserMetadataDto {
  displayName: string;
  email: string;
  email_verified: boolean;
  phone: string;
  phone_verified: boolean;
  sub: string;
}
