/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import type { UserMetadataDto } from "./userMetadataDto";

export interface UserIdentityDto {
  identity_id: string;
  id: string;
  user_id: string;
  identity_data: UserMetadataDto;
  provider: string;
  last_sign_in_at: string;
  created_at: string;
  updated_at: string;
  email: string;
}
