/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Retrieve all transactions
 */
export const getAllTransactionsQueryParams = zod.object({
  "card": zod.string().optional().describe('Card ID'),
  "dependent": zod.string().optional().describe('Dependent ID'),
  "purchaseName": zod.string().optional().describe('Purchase name'),
  "purchaseCategory": zod.string().optional().describe('Purchase category'),
  "purchaseDate": zod.string().optional().describe('Purchase date'),
  "installments": zod.string().optional().describe('Number of installments'),
  "installmentDates": zod.string().optional().describe('Installment dates. E.g. 02/2025, 05/2025')
})

export const getAllTransactionsResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "result": zod.array(zod.string())
})

/**
 * @summary Create a new transaction
 */
export const createTransactionBody = zod.object({
  "cardId": zod.string(),
  "purchaseName": zod.string(),
  "purchaseCategory": zod.string(),
  "description": zod.string(),
  "amount": zod.number(),
  "installments": zod.number(),
  "purchaseDate": zod.string(),
  "dependentId": zod.string()
})

/**
 * @summary Retrieve a transaction by ID
 */
export const findTransactionByFiltersQueryParams = zod.object({
  "id": zod.string().optional().describe('Transaction ID'),
  "purchaseName": zod.string().optional().describe('Purchase name'),
  "dependentId": zod.string().optional().describe('Dependent ID'),
  "cardId": zod.string().optional().describe('Card ID'),
  "purchaseCategory": zod.string().optional().describe('Purchase category'),
  "description": zod.string().optional().describe('Description'),
  "purchaseDate": zod.string().optional().describe('Purchase date')
})

export const findTransactionByFiltersResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "result": zod.object({

})
})

/**
 * @summary Update a transaction
 */
export const updateTransactionParams = zod.object({
  "id": zod.string().describe('Transaction ID')
})

export const updateTransactionBody = zod.object({
  "purchaseName": zod.string(),
  "purchaseCategory": zod.string(),
  "description": zod.string(),
  "amount": zod.number(),
  "installments": zod.number(),
  "purchaseDate": zod.string(),
  "dependentId": zod.string()
})

export const updateTransactionResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "data": zod.object({

})
})

/**
 * @summary Delete a transaction
 */
export const deleteTransactionParams = zod.object({
  "id": zod.string().describe('Transaction ID')
})

export const deleteTransactionResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "data": zod.object({

})
})

