/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Get all users
 */
export const getAllUsersResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "result": zod.array(zod.string())
})

/**
 * @summary Change a user's role
 */
export const changeUserRoleBody = zod.object({
  "userId": zod.string().describe('ID of the user'),
  "newRole": zod.enum(['USER', 'ADMIN', 'SUPER_ADMIN']).describe('New role for the user').describe('New role for the user')
})

export const changeUserRoleResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "data": zod.object({

})
})

/**
 * @summary Delete a user by ID
 */
export const deleteUserByIdParams = zod.object({
  "id": zod.string().describe('User ID')
})

export const deleteUserByIdResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "data": zod.object({

})
})

/**
 * @summary Update a user by ID
 */
export const updateUserByIdParams = zod.object({
  "id": zod.string().describe('User ID')
})

export const updateUserByIdBody = zod.object({
  "name": zod.string().optional().describe('Name of the user'),
  "email": zod.string().optional().describe('Email of the user'),
  "phone": zod.string()
})

export const updateUserByIdResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "data": zod.object({

})
})

/**
 * @summary Get current logged in user
 */
export const getCurrentUserResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "result": zod.object({

})
})

/**
 * @summary Update current logged in user
 */
export const updateCurrentUserBody = zod.object({
  "name": zod.string().optional().describe('Name of the user'),
  "email": zod.string().optional().describe('Email of the user'),
  "phone": zod.string()
})

export const updateCurrentUserResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "data": zod.object({

})
})

/**
 * @summary Delete current logged in user
 */
export const deleteCurrentUserResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "data": zod.object({

})
})

