/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ResponseBadRequestDto,
  ResponseForbiddenDto,
  ResponseInternalServerErrorDto,
  ResponseNotFoundDto,
  ResponseUnauthorizedDto,
  ResultDeleteUserDto,
  ResultFindAllUsersDto,
  ResultFindOneUserDto,
  ResultUpdateUserRoleDto,
  UpdateUserDto,
  UpdateUserRoleDto,
} from "../../model";

import { customInstance } from "../../../lib/axios";
import type { ErrorType, BodyType } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get all users
 */
export const getAllUsers = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResultFindAllUsersDto>(
    { url: `/users`, method: "GET", signal },
    options,
  );
};

export const getGetAllUsersQueryKey = () => {
  return [`/users`] as const;
};

export const getGetAllUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllUsers>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllUsersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUsers>>> = ({
    signal,
  }) => getAllUsers(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllUsers>>
>;
export type GetAllUsersQueryError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseNotFoundDto
  | ResponseInternalServerErrorDto
>;

export function useGetAllUsers<
  TData = Awaited<ReturnType<typeof getAllUsers>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUsers>>,
          TError,
          Awaited<ReturnType<typeof getAllUsers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllUsers<
  TData = Awaited<ReturnType<typeof getAllUsers>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUsers>>,
          TError,
          Awaited<ReturnType<typeof getAllUsers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllUsers<
  TData = Awaited<ReturnType<typeof getAllUsers>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all users
 */

export function useGetAllUsers<
  TData = Awaited<ReturnType<typeof getAllUsers>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllUsersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Change a user's role
 */
export const changeUserRole = (
  updateUserRoleDto: BodyType<UpdateUserRoleDto>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ResultUpdateUserRoleDto>(
    {
      url: `/users/change-role`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateUserRoleDto,
    },
    options,
  );
};

export const getChangeUserRoleMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changeUserRole>>,
    TError,
    { data: BodyType<UpdateUserRoleDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof changeUserRole>>,
  TError,
  { data: BodyType<UpdateUserRoleDto> },
  TContext
> => {
  const mutationKey = ["changeUserRole"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof changeUserRole>>,
    { data: BodyType<UpdateUserRoleDto> }
  > = (props) => {
    const { data } = props ?? {};

    return changeUserRole(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChangeUserRoleMutationResult = NonNullable<
  Awaited<ReturnType<typeof changeUserRole>>
>;
export type ChangeUserRoleMutationBody = BodyType<UpdateUserRoleDto>;
export type ChangeUserRoleMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Change a user's role
 */
export const useChangeUserRole = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof changeUserRole>>,
      TError,
      { data: BodyType<UpdateUserRoleDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof changeUserRole>>,
  TError,
  { data: BodyType<UpdateUserRoleDto> },
  TContext
> => {
  const mutationOptions = getChangeUserRoleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete a user by ID
 */
export const deleteUserById = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ResultDeleteUserDto>(
    { url: `/users/delete/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteUserByIdMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUserById>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUserById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteUserById"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUserById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteUserById(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUserByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUserById>>
>;

export type DeleteUserByIdMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Delete a user by ID
 */
export const useDeleteUserById = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUserById>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteUserById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteUserByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Update a user by ID
 */
export const updateUserById = (
  id: string,
  updateUserDto: BodyType<UpdateUserDto>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ResultUpdateUserRoleDto>(
    {
      url: `/users/edit/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateUserDto,
    },
    options,
  );
};

export const getUpdateUserByIdMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserById>>,
    TError,
    { id: string; data: BodyType<UpdateUserDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserById>>,
  TError,
  { id: string; data: BodyType<UpdateUserDto> },
  TContext
> => {
  const mutationKey = ["updateUserById"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserById>>,
    { id: string; data: BodyType<UpdateUserDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateUserById(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserById>>
>;
export type UpdateUserByIdMutationBody = BodyType<UpdateUserDto>;
export type UpdateUserByIdMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Update a user by ID
 */
export const useUpdateUserById = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUserById>>,
      TError,
      { id: string; data: BodyType<UpdateUserDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUserById>>,
  TError,
  { id: string; data: BodyType<UpdateUserDto> },
  TContext
> => {
  const mutationOptions = getUpdateUserByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get current logged in user
 */
export const getCurrentUser = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ResultFindOneUserDto>(
    { url: `/users/me`, method: "GET", signal },
    options,
  );
};

export const getGetCurrentUserQueryKey = () => {
  return [`/users/me`] as const;
};

export const getGetCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({
    signal,
  }) => getCurrentUser(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUser>>
>;
export type GetCurrentUserQueryError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseNotFoundDto
  | ResponseInternalServerErrorDto
>;

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current logged in user
 */

export function useGetCurrentUser<
  TData = Awaited<ReturnType<typeof getCurrentUser>>,
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseNotFoundDto
    | ResponseInternalServerErrorDto
  >,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCurrentUserQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update current logged in user
 */
export const updateCurrentUser = (
  updateUserDto: BodyType<UpdateUserDto>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ResultUpdateUserRoleDto>(
    {
      url: `/users/me`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateUserDto,
    },
    options,
  );
};

export const getUpdateCurrentUserMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCurrentUser>>,
    TError,
    { data: BodyType<UpdateUserDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCurrentUser>>,
  TError,
  { data: BodyType<UpdateUserDto> },
  TContext
> => {
  const mutationKey = ["updateCurrentUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCurrentUser>>,
    { data: BodyType<UpdateUserDto> }
  > = (props) => {
    const { data } = props ?? {};

    return updateCurrentUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCurrentUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCurrentUser>>
>;
export type UpdateCurrentUserMutationBody = BodyType<UpdateUserDto>;
export type UpdateCurrentUserMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Update current logged in user
 */
export const useUpdateCurrentUser = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCurrentUser>>,
      TError,
      { data: BodyType<UpdateUserDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCurrentUser>>,
  TError,
  { data: BodyType<UpdateUserDto> },
  TContext
> => {
  const mutationOptions = getUpdateCurrentUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete current logged in user
 */
export const deleteCurrentUser = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ResultDeleteUserDto>(
    { url: `/users/me`, method: "DELETE" },
    options,
  );
};

export const getDeleteCurrentUserMutationOptions = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCurrentUser>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCurrentUser>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["deleteCurrentUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCurrentUser>>,
    void
  > = () => {
    return deleteCurrentUser(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCurrentUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCurrentUser>>
>;

export type DeleteCurrentUserMutationError = ErrorType<
  | ResponseBadRequestDto
  | ResponseUnauthorizedDto
  | ResponseForbiddenDto
  | ResponseInternalServerErrorDto
>;

/**
 * @summary Delete current logged in user
 */
export const useDeleteCurrentUser = <
  TError = ErrorType<
    | ResponseBadRequestDto
    | ResponseUnauthorizedDto
    | ResponseForbiddenDto
    | ResponseInternalServerErrorDto
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCurrentUser>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCurrentUser>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getDeleteCurrentUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
