/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Credit Card Planner API
 * The API for the Credit Card Planner application
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * Retrieve all categories for the authenticated user.
 * @summary Get all categories
 */
export const getAllCategoriesQueryParams = zod.object({
  "name": zod.string().optional().describe('Filter by category name')
})

export const getAllCategoriesResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "result": zod.array(zod.string())
})

/**
 * @summary Create a new category
 */
export const createCategoryBody = zod.object({
  "name": zod.string(),
  "icon": zod.string(),
  "color": zod.string()
})

export const createCategoryResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "data": zod.object({

})
})

/**
 * Find a specific category by ID or name.
 * @summary Find a category
 */
export const findCategoryQueryParams = zod.object({
  "name": zod.string().optional().describe('Category name')
})

export const findCategoryResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "result": zod.object({

})
})

/**
 * @summary Update a category
 */
export const updateCategoryParams = zod.object({
  "name": zod.string().describe('Category Name')
})

export const updateCategoryBody = zod.object({
  "name": zod.string(),
  "icon": zod.string(),
  "color": zod.string()
})

export const updateCategoryResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "data": zod.object({

})
})

/**
 * @summary Delete a category
 */
export const deleteCategoryParams = zod.object({
  "name": zod.string().describe('Category name')
})

export const deleteCategoryResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "statusCode": zod.number(),
  "count": zod.number(),
  "data": zod.object({

})
})

